name: ligo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ipykernel=6.29
  - numpy=2.0
  - scipy=1.13
  - matplotlib=3.9
  - h5py=3.12
  - decorator=5.1
  - pip
  - pip:
      - cycler==0.12
      - contourpy==1.3
      - fonttools==4.55
      - pyparsing==3.2
